### ISSUE TITLE
add some resources

### ISSUE THREAD

**Issue by safareli** [SimonRichardson/fantasia#5]
It will be really nice if you could add some resources so others (including me) could really understand those data structures. 

In one project I'm actually using Free from [DrBoolean/freeky](https://github.com/DrBoolean/freeky) and understend the ideas of Free and why is it usefull but it is kinda too recursive for me, and I Feel like I did not quite understand it.  then I found this repo and i'm kinda lost...

so it will be really nice if you add some resources ❤️

**Comment by SimonRichardson** [comment]
Just a note, if you don't like the recursive nature of [DrBoolean/freeky](https://github.com/DrBoolean/freeky), then you'll like this about the same! 

It does the same or similar sort of recursion, in fact I think freeky is a very good implementation of the free monad. This implementation is based on scalaz and purescript implementations, although this was done before the learnings of http://okmij.org/ftp/Haskell/zseq.pdf and https://github.com/purescript/purescript-free#benchmarks

I've not got much time atm to move over the current implementation, I suspect it's not a lot of work, but requires a lot of thinking.

@DrBoolean want to chime in?

**Comment by DrBoolean** [comment]
I think jdegoes said it best in the midst of this tweet storm about modeling computation: https://twitter.com/jdegoes/status/719963510612971520

The inductive nature is exactly why it's sequential (monadic).

I made my lib because I wanted to redefine a bunch of monads in terms of Free and compose them all. I based it on a different paper called Free(er) monads.

There's totally different ways of implementing it under the hood like a queue and such. I'd like to explore that because we're having great luck using this with heavy dev-ops based workflows.

Anyways, to gain an understanding of this lib, i hacked on the examples for a bit to get a feel for it. I recommend playing with the KVO or Tweet one to start.

**Comment by safareli** [comment]
Thenks!
